spring.application.name=mano

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://rzwifjcbiezzhrfmrbeh.supabase.co/auth/v1
app.cors.allowed-origin=http://localhost:5173
supabase.username=you.azt@gmail.com
supabase.password=cD#1!BPAYMkx8m0JdK$c
